# Site settings
title: GitBuilding
email: julian@julianstirling.co.uk
description: > # this means to ignore newlines until "baseurl:"
  For documenting hardware projects with minimal effort, so you can stop writing and git building.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["README.md", vendor]
include: ['_pages']
gems:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
baseurl: /git-building-website/
